---
- name: install docker
  hosts: all
  become: true
  become_user: root
  tasks:

    - name: upgrade all packages
      yum: name=* state=latest

    - name: Install required pkgs
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: set skip skip_if_unavailable
      ansible.builtin.shell:
        cmd: yum-config-manager --save --setopt=docker-ce-stable.skip_if_unavailable=true

    - name: Install Docker
      yum:
        name:
          - docker
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user ec-2 to docker group
      user:
        name: ec-2
        groups: docker
        append: yes
      become: yes